events {}

http {
    upstream auth_service {
        server auth:8000;
    }

    server {
        listen 80;

        # весь auth просто проксируем
        location /auth/ {
            proxy_pass http://auth_service/;
        }
    }
}